### PR TITLE
ITP method implementation

### PR DESCRIPTION
**Pull request by yash2798**
Tackles this [#184](https://github.com/SciML/NonlinearSolve.jl/issues/184)

### CODE REVIEW

**Comment by yash2798** [comment]
@ChrisRackauckas I am kinda confused why such an error in only some test cases is happening. Do you have any inputs that might help? The code seems alright but maybe can you review it once?

**Comment by ChrisRackauckas** [comment]
How much has the solution converged?

**Comment by yash2798** [comment]
> How much has the solution converged?

The solution (root of the function) has converged well upto the tolerance. This can be also be seen as the tests for this also pass. Just the AD tests fail only for a handful values for the parameter p.

**Comment by yash2798** [comment]
`g = function (p)
    probN = IntervalNonlinearProblem{false}(f, typeof(p).(tspan), p)
    sol = solve(probN, Itp())
    return sol.u
end

for p in 1.1:0.1:100.0
    @test g(p) ≈ sqrt(p)
    @test ForwardDiff.derivative(g, p) ≈ 1 / (2 * sqrt(p))
end`

All these tests `@test g(p) ≈ sqrt(p)` pass.

**Comment by ChrisRackauckas** [comment]
How close to zero is the valudation?

**Comment by ChrisRackauckas** [comment]
Try and recreate the derivative calculation in the REPL: https://github.com/SciML/SimpleNonlinearSolve.jl/blob/main/src/ad.jl#L2-L28

**Comment by yash2798** [comment]
okay i'll take a look

**Comment by yash2798** [comment]
@ChrisRackauckas I tried doing the derivative calc in the repl but nothing significant came up. Also, I am a little confused about what this function `scalar_nlsolve_ad` does? I can see that it is called in some dispatches written down after that but if I am not mistaken i don't see any dispatches that handle any algorithm except the Bisection one?

https://github.com/SciML/SimpleNonlinearSolve.jl/blob/b2a43e0c2a8550be9c714c7d190591a4aa0f2faf/src/ad.jl#L51

**Review by oscardssmith — APPROVED** [review]

**Comment by oscardssmith** [comment]
The broad strokes of this look good.

**Comment by oscardssmith** [comment]
I just mean that all the tests seem to suggest that it is broken.

**Pull request closed without merging**
